Debugging isssue

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -39,8 +39,12 @@ jobs:
 
       - name: Set EC2 IP to Environment Variable
         run: |
-          IP=$(cd iac && terraform output -raw instance_ip | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}')
-          echo " EC2_IP=$IP " >> $GITHUB_ENV
+          IP=$(cd iac && terraform output -raw instance_ip | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}' | tr -d '\r')
+          if [[ -z "$IP" ]]; then
+            echo "IP is empty. Terraform output failed."
+            exit 1
+          fi
+          echo "EC2_IP=$IP" >> $GITHUB_ENV
           echo "EC2 Public IP: $IP"
 
       - name: Setup SSH Key
